.github/workflows/ci.yaml.example, install-binary.sh, secrets.sh, test.sh
it's almost a rewrite of the shell script for helm script.
I remove all bash related shell code and replace it with POSIX feature. The script will run on almost any posix compatible shell. The scripts is also compliant to shellcheck.
ZSH (MacOS default shell) and ash (Alpine default shell) should now out of the box supported. gnu-getops is not required anymore.
All tests from test.sh are green under MacOS 10.15.4 (zsh, bash 3.2.57) and Alpine 3.11 (ash)
Additional features:
All helm commands are supported now. Before this only install|template|upgrade|lint|diff are supported. If plugins like kubeval are installed this script need to be modified. The PR remove the limitation.
=> Add POSIX compatibility

contrib/release.sh, scripts/run.sh, tests/7-lint.bats, tests/helper.bash
Add tests for special paths in secret.yaml paths like `()!\e@`
=> Harding against special charts in path

scripts/drivers/_custom.sh
=> detect gnu sed on any system

tests/lib/helper.bash, tests/unit/dec.bats, tests/unit/plugin-install.bats
Tests leave a lot of tmp files/dirs when run, this diff leaves only tmpfiles leaked by plugin/drivers.
From `main` branch as of `be47fb3` + https://github.com/jkroepke/helm-secrets/pull/89 I found `lint.bats`, `template.bats` and `vault.bats` to leak 0-byte tmpfiles, not from the tests themselves.
=> Cleanup temporary files/dirs from tests.

tests/lib/helper.bash
Introduced in #90 
See https://github.com/bats-core/bats-file/pull/31
=> Use rm instead temp_del.

.editorconfig, CHANGELOG.md, scripts/commands/helm.sh, scripts/drivers/_custom.sh, scripts/lib/common.sh, scripts/lib/file/custom.sh, scripts/lib/file/http.sh, scripts/run.sh, tests/unit/vault.bats
`TMPDIR` need to be exported, otherwise `mktemp` don't care.
On Mac OS, `TMPDIR` is not going to respect. The proposal is creating an own directory inside the fixed temp directory. 
See https://unix.stackexchange.com/q/555058 about the mac os specific behaivor
Closes #89 
Fixes #88
=> Cleanup temporary files

scripts/drivers/_custom.sh, scripts/drivers/vault.sh, tests/assets/custom-driver.sh, tests/assets/values/vault/secrets.yaml, tests/assets/values/vault/seed.sh
allow path like:
secret/devops/certificates/internal.domain-with-hyphen.com#file.crt
=> Allow dot, asterisk and underscore for vault path

README.md, USAGE.md
Thanks for maintaining this useful plugin. I found it to be the most straightforward way to integrate secrets management with our GitOps workflow.
This PR adds a snippet to the documentation showing how to integrate `helm-secrets` with Argo CD.
=> Add usage example with Argo CD to docs

CHANGELOG.md, docs/ArgoCD Integration.md, docs/Feature Flags.md, docs/Home.md, docs/_Footer.md, scripts/lib/expand_vars_strict.sh, scripts/lib/file/http.sh, scripts/run.sh, tests/unit/template.bats
=> Add variable expansion to URLs for values

CHANGELOG.md, scripts/commands/terraform.sh, tests/unit/terraform.bats
Fix broken json output on some systems
Running my TF on AWS CodeBuild image: `aws/codebuild/standard:5.0`
Typical usage:
`$ helm secrets terraform secrets/myproject/nginx/secrets.yaml`
Would output: 
```json
{"content_base64":"<base64 coded content
of value file>"}
```
(notice unexpected new line)
This is no longer a valid json.
This happens because `base64` on some platforms wraps output by default
ref: https://superuser.com/questions/1225134/why-does-the-base64-of-a-string-contain-n
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #193
Complete these before marking the PR as …
=> Fix broken json output on some systems

.editorconfig, .gitattributes, .github/workflows/ci.yaml, CHANGELOG.md, README.md, docker-compose.yaml, docs/Usage.md, scripts/commands/enc.sh, scripts/commands/help.sh, scripts/commands/patch.sh, scripts/drivers/sops.sh, scripts/lib/common.sh, scripts/lib/file/custom.sh, scripts/run.sh, scripts/wrapper/run.cmd, scripts/wrapper/sh.cmd, tests/lib/helper.bash, tests/unit/template.bats
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #214 
=> Fix helm protocol handler on windows

docs/Secret Driver.md
There is a copy/paste typo in the Drivers documentation.
This MR fixes it.
=> Fix probable copy/paste typo

docs/ArgoCD Integration.md
choose string interpolation (`""`) and escape variables (`${}`) for POSIX-compatibility
The wiki documentation proposes to run a command that doesn't yield a positive outcome when copy and pasted.
Explicit string interpolation and variable escaping will help to find the correct data.
Thank you for having a look!
=> Update ArgoCD Integration.md

CHANGELOG.md, scripts/backends/sops.sh, tests/assets/values/sops/.gitattributes, tests/assets/values/sops/some-secrets.windows.yaml, tests/unit/decrypt.bats
Signed-off-by: Marco Poli <marco.a.poli@gmail.com>
**What this PR does / why we need it**: fixes detection of SOPS YAML files with Windows line-endings (CR LF)
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #290 
**Special notes for your reviewer**: the .gitattributes is there to prevent that one specific YAML file from having its line-endings automatically converted.
=> fix YAML detection for Windows line-endings (#290)

scripts/backends/vals.sh
fix output and exit the process in case of templating error when using `--evaluate-templates` flag
it fixes the situation when some Vals backend is unavailable or any issue with resolving secrets. before PR these errors were ignored and be written in templated files that leads to strange errors when Helm tries to apply these files to K8s
=> fix output to handle error when using --evaluate-templates

docs/ArgoCD Integration.md
Small fix to ArgoCD integration doc to use latest helm secrets version.
=> Updated helm-secrets version in ArgoCD integration documentation

.github/workflows/ci.yaml, .github/workflows/release.yaml, CHANGELOG.md, docs/ArgoCD Integration.md, scripts/lib/common.sh, scripts/run.sh, scripts/wrapper/helm.sh, tests/unit/template.bats
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #337 
=> Migrations for ArgoCD multi source application limitations

CHANGELOG.md, scripts/lib/http.sh
The equal sign in the curl arguments is superfluous.
It fixes an error:  
`curl: option --netrc-file=/custom-tools/.netrc: is unknown`
=> Fix curl arguments (#342

CHANGELOG.md, docs/ArgoCD Integration.md, docs/Usage.md, scripts/commands/help.sh, scripts/lib/file.sh, scripts/run.sh, tests/unit/template.bats
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #381
=> Add HELM_SECRETS_DECRYPT_SECRETS_IN_TMP_DIR

CHANGELOG.md, scripts/commands/downloader.sh, tests/unit/template.bats
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #385 
=> `secrets+*-import://` added syntax checks

docs/ArgoCD Integration.md
Correct curl 404 error in sops release url in the download-tools init container.
=> Fix download-tools init container sops release url, append .amd64

docs/ArgoCD Integration.md
sops produces amd64 and arm64 binary flavors for Linux now, filename has changed accordingly.
=> fix(docs/argocd-integration): Update binary name of sops release

scripts/commands/helm.sh, tests/unit/template.bats
Fixes the parsing of array values passed through ```--set```
**Which issue this PR fixes** : fixes #418
=> fix: parsing of array values

CHANGELOG.md, docs/Secret Backends.md, examples/backends/onepassword.sh, tests/README.md, tests/assets/values/custom-backend/onepassword-secrets.yaml, tests/lib/helper.bash, tests/lib/setup_suite.bash, tests/unit/secret-backends.bats
This PR adds the 1Password CLI as an additional custom backend.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #424
I really wanted to make the tests work as well, but for some reason `op` always thinks it is not authenticated.
Manually running the decrypt function with the test file does work as expected.
I tried a few things to make this work with BATS:
- The configuration directory for op `~/.config/op` was copied to `${HOME}/.config/op` within `setup_suite.bash`
- Additionally I tried to add a session token via an exported env var or using the `--session` parameter of `op`
- Trying to authenticate …
=> Add the 1Password CLI as a custom backend

Dockerfile, docs/ArgoCD Integration.md
`kubectl` on the provided URI doesn't use git tag, [but actual Kubernetes version](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/). Meaning trying to download `0.21.0` yields 404.
Some places used `kubectl` in version 1.26.1, but Dockerfile was stuck on 1.21.0 for some reason. Thus the Dockerfile couldn't be built, as suggested [here in docs](https://github.com/jkroepke/helm-secrets/wiki/ArgoCD-Integration#option-2-init-container). I bumped it to latest.
=> Bump kubectl to 1.30.1

docs/Values.md
`helm-git` path separator is now optional, correctly supports multi-level repo (GitLab style) and has the `package` option.
=> docs: update helm-git sample

CHANGELOG.md, scripts/commands/decrypt.sh, scripts/commands/encrypt.sh
Minor change in the example of `decrypt` / `encrypt` commands. The examples still used `dec` and `enc` from version 3.
=> docs: update help for decrypt/encrypt

.github/workflows/ci.yaml, CHANGELOG.md, scripts/commands/helm.sh
=> remove dependency on `xargs`

scripts/lib/common.sh
**What this PR does / why we need it**: Fix downloader plugin, if helm is installed as native binary inside WSL
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #477 
=> WSL: fix downloader plugin

USERS.md, docs/ArgoCD Integration.md
**What this PR does / why we need it**: The Dockerfile in the documentation mentions the old ArgoCD repository on Docker Hub. The new one, with latest updated images, is located on quay.io. I updated the example Dockerfile for the developers to be able to copy its content and make it work as is.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
**Special notes for your reviewer**: I also added Sopra Steria in the `USERS.md` file, should I do a separate PR?
=> Update ArgoCD example Dockerfile in documentation

CHANGELOG.md, scripts/commands/helm.sh
=> fix helm_wrapper does not honor escaped commas in --set arguments

CHANGELOG.md, plugin.yaml
The plugin.yaml does not accept the deprecated command key anymore since helm v3.18.0
See docs: [helm plugin](https://helm.sh/docs/topics/plugins/#the-pluginyaml-file)
**Which issue this PR fixes**:
fixes #530 
=> fix(#530): move deprecated command to platformCommand section
