scripts/run.sh
tests/2-dec.bats

Fixes: https://github.com/zendesk/helm-secrets/issues/151

Optionally decrypt helm secrets in a temporary directory

---

.gitmodules
scripts/commands/edit.sh
scripts/install.sh
scripts/run.sh
tests/helper.bash
tests/it/00-setup.bats
tests/it/01-plugin-install.bats
tests/it/11-install.bats
tests/it/12-upgrade.bats
tests/it/13-diff.bats
tests/it/99-cleanup.bats
tests/unit/00-setup.bats
tests/unit/01-plugin-install.bats
tests/unit/02-secret-driver.bats
tests/unit/11-view.bats
tests/unit/12-dec.bats
tests/unit/13-enc.bats
tests/unit/14-edit.bats
tests/unit/15-clean.bats
tests/unit/16-lint.bats
tests/unit/17-template.bats
tests/unit/18-kubeval.bats
tests/unit/99-cleanup.bats

Use bats-file instead own asserts

Added bats-file

---

CHANGELOG.md
scripts/commands/helm.sh
tests/it/diff.bats
tests/it/install.bats
tests/it/upgrade.bats
tests/unit/kubeval.bats
tests/unit/lint.bats
tests/unit/template.bats

Support parameters like --values=secrets.yaml

---

CHANGELOG.md
README.md
scripts/install.sh

Fixes: https://github.com/zendesk/helm-secrets/issues/164

Allow override sops version on installation.

---

.github/workflows/ci.yaml

Blocky by https://github.com/mdgreenwald/mozilla-sops-action/issues/10

Unify CI tests

---

CHANGELOG.md
USAGE.md
plugin.yaml
scripts/commands/downloader.sh
scripts/commands/helm.sh
scripts/downloader.sh
scripts/run.sh
tests/it/diff.bats
tests/it/install.bats
tests/it/upgrade.bats
tests/unit/template.bats

Refactor as a subcommand in order to support :
- remote files
- all secrets drivers (sops, vault, ...)

Refactor downloader

---

CHANGELOG.md
scripts/drivers/_custom.sh
scripts/drivers/vault.sh

Other drivers like #53 could re-use the well tested vault logic

externalize vault driver logic

---

.github/workflows/ci.yaml

Blocked: https://github.com/zsh-users/zsh-docker/pull/19

Test against zsh

---

README.md

Hey
I thought it might be useful ;)
Cheers

fix(doc): secret driver environment variable name

---

CHANGELOG.md
scripts/drivers/_custom.sh
tests/assets/values/vault/some-secrets.yaml

Strip yaml doc separator

---

.github/workflows/ci.yaml
scripts/drivers/_custom.sh

Fixed "grep: Invalid range end" if locale is different then C

---

.github/workflows/ci.yaml
CHANGELOG.md
scripts/lib/common.sh
scripts/run.sh
tests/unit/vault.bats

Fixed mktemp: too few X's in template on mac os + Add tests for coreutils on mac os 

---

README.md

Related : https://github.com/jkroepke/helm-secrets/issues/100

add sops binary override parameter documentation

---

.github/workflows/ci.yaml
CHANGELOG.md
plugin.yaml
scripts/commands/enc.sh
scripts/commands/helm.sh
scripts/lib/common.sh
scripts/run.sh
scripts/wrapper/sh.cmd
tests/lib/helper.bash
tests/unit/dec.bats

Improve cygwin compatibility

---

scripts/drivers/sops.sh

Respect HELM_SECRETS_SOPS_PATH (as it's documented)

---

README.md
examples/doppler/.helmignore
examples/doppler/Chart.yaml
examples/doppler/secrets.yaml
examples/doppler/templates/NOTES.txt
examples/doppler/templates/_helpers.tpl
examples/doppler/templates/deployment.yaml
examples/doppler/templates/hpa.yaml
examples/doppler/templates/ingress.yaml
examples/doppler/templates/service.yaml
examples/doppler/templates/serviceaccount.yaml
examples/doppler/templates/tests/test-connection.yaml
examples/doppler/values.yaml
scripts/drivers/doppler.sh

Add a new driver for [Doppler](https://doppler.com) secret manager.

[Driver] Doppler

---

.github/workflows/ci.yaml
scripts/commands/downloader.sh

Test with UBI8

---

CHANGELOG.md
docs/ARGOCD.md
docs/USAGE.md
plugin.yaml
scripts/commands/downloader.sh
scripts/lib/common.sh
tests/it/install.bats
tests/unit/template.bats

Add secrets+gpg-import-kubernetes://

---

docs/ARGOCD.md

Argo CD Integration Documentation
fixes #159

Improve the Argo CD Integration Documentation #159

---

docs/ARGOCD.md

Additional instructions for how to use this plugin with ArgoCD
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*:
Helps users who are using GCP KMS with sops and this plugin

docs:argocd-gcp-kms

---

CHANGELOG.md
scripts/commands/downloader.sh

Implement stricter protocol handler

---

.github/workflows/ci.yaml

Fix coverage

---

README.md
scripts/commands/downloader.sh
scripts/lib/file/custom.sh
tests/it/install.bats

Minor improvements

---

CHANGELOG.md
scripts/lib/http.sh

**What this PR does / why we need it**: https://everything.curl.dev/usingcurl/netrc

Enable .netrc for http based values

---

.gitignore
docs/ArgoCD Integration.md
docs/Usage.md
docs/Values.md
scripts/lib/http.sh

Explain remote value files

---

.github/workflows/ci.yaml
.simplecov
CODE_OF_CONDUCT.md
tests/it/diff.bats
tests/it/install.bats
tests/it/upgrade.bats

Add coverage to ITs

---

docs/ArgoCD Integration.md

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #180

Fix typos in ArgoCD Integration documentation

---

README.md

Fixes a link the docs
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes https://github.com/jkroepke/helm-secrets/issues/85#issuecomment-1027449938
**Special notes for your reviewer**: Small update, purposely no entry in change log.
Decided this change does not warrant a CHANGELOG.md entry.

[README] updated with correct path to the example of how to use helm-secrets with terraform.

---

docs/ArgoCD Integration.md
scripts/run.sh
tests/lib/helper.bash
tests/unit/template.bats

Improve compatibility with helm wrapper

Improve helm-secrets wrapper

---

CHANGELOG.md
docs/Security in shared environments.md
scripts/commands/dec.sh
scripts/commands/downloader.sh
scripts/lib/common.sh
scripts/lib/file.sh
tests/assets/values/sops/secrets.symlink.yaml
tests/lib/helper.bash
tests/unit/template.bats

Add hardening for values file paths

---

scripts/run.sh

Fixes run helm-secrets on WSL
**Which issue this PR fixes**:
Fixes #197 

Fixes run helm-secrets on WSL

---

README.md
docs/ArgoCD Integration.md

**What this PR does / why we need it**: Update ArgoCD Integration to match the new capabilities on ArgoCD 2.3
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #185

Update ArgoCD Integration to match the new capabilities on ArgoCD 2.3

---

docs/ArgoCD Integration.md

See https://github.com/jkroepke/helm-secrets/issues/185#issuecomment-1092766674

Better documentation of helm.valuesFileSchemes

---

CHANGELOG.md
scripts/drivers/sops.sh

Change detection of sops file

---

CHANGELOG.md
Dockerfile
docs/ArgoCD Integration.md
scripts/commands/clean.sh
scripts/commands/dec.sh
scripts/commands/downloader.sh
scripts/commands/edit.sh
scripts/commands/enc.sh
scripts/commands/helm.sh
scripts/commands/view.sh
scripts/drivers/vault.sh
scripts/lib/common.sh
scripts/lib/file.sh
scripts/lib/file/http.sh
scripts/lib/http.sh
scripts/wrapper/sh.cmd

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #212 

Add better error handling of downloading files

---

scripts/run.sh

Replace dirname with HELM_PLUGIN_DIR

---

.github/workflows/ci.yaml
docker-compose.yaml
tests/lib/helper.bash
tests/unit/edit.bats
tests/unit/gitops.bats
tests/unit/secret-driver.bats
tests/unit/view.bats

Optimize vault tests

---

.github/workflows/ci.yaml
tests/lib/helper.bash
tests/unit/clean.bats
tests/unit/dec.bats
tests/unit/lint.bats

Optimize tests execution

---

.github/workflows/ci.yaml
CHANGELOG.md
scripts/wrapper/sh.cmd

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #225 

Prefer gpg4win over builtin gpg installations

---

.github/workflows/ci.yaml
README.md
docs/ArgoCD Integration.md
docs/Cloud Integration.md
docs/Feature Flags.md
docs/Installation.md

Cloud Integration

---

.github/workflows/ci.yaml
CHANGELOG.md
scripts/backends/sops.sh
scripts/backends/vals.sh
scripts/commands/dec.sh
scripts/commands/helm.sh
scripts/lib/common.sh
scripts/lib/file/http.sh
tests/assets/values/sops/files/file.json
tests/assets/values/sops/files/file.properties
tests/assets/values/sops/files/file.txt
tests/assets/values/sops/files/file.yaml
tests/assets/values/vals/files/file.json
tests/assets/values/vals/files/file.txt
tests/assets/values/vals/files/file.yaml
tests/unit/gitops.bats
tests/unit/template.bats

**What this PR does / why we need it**: 
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: See #249 

Support for decrypting files defined via --set-file

---

CHANGELOG.md
plugin.yaml
scripts/commands/downloader.sh
tests/it/diff.bats
tests/it/install.bats
tests/it/upgrade.bats
tests/unit/template.bats

Remove sops and secret protocol handler

---

docs/ArgoCD Integration.md
scripts/backends/sops.sh
scripts/backends/vals.sh
scripts/commands/downloader.sh
scripts/commands/view.sh
scripts/lib/file.sh
scripts/lib/file/http.sh
tests/unit/template.bats

Fix: non yaml files on --set-file=secrets://

---

tests/unit/encrypt.bats
tests/unit/lint.bats
tests/unit/template.bats

remove debug from tests

---

.github/workflows/ci.yaml

Update kind version

---

CHANGELOG.md
scripts/commands/helm.sh
tests/unit/template.bats

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #273 

Fix comma separated values with --set

---

CHANGELOG.md
scripts/wrapper/sh.cmd

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #281

Support for shell installed via scoop

---

.github/workflows/ci.yaml
tests/lib/setup_suite.bash

fix cygwin

---

CHANGELOG.md
scripts/backends/sops.sh

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #292 

fix performance issues for large sops files

---

.github/workflows/ci.yaml

ci: Resolve all warnings

---

CHANGELOG.md
scripts/backends/vals.sh

Performance issues with large value files on vals backend

---

scripts/lib/file.sh
scripts/lib/file/custom.sh
scripts/lib/file/http.sh
scripts/lib/file/local.sh

Remove dead code

---

CHANGELOG.md
README.md
docs/Usage.md
scripts/backends/vals.sh
scripts/commands/helm.sh
scripts/commands/help.sh
scripts/commands/post-renderer.sh
scripts/run.sh
tests/assets/values/vals/templates/template.yaml
tests/lib/setup_suite.bash
tests/unit/lint.bats
tests/unit/secret-backends.bats
tests/unit/template.bats

Evaluating helm templates

---

CHANGELOG.md
scripts/lib/file/http.sh
tests/unit/template.bats

**What this PR does / why we need it**: this PR is improving support of remote value files whose URL contains query string arguments
**Which issue this PR fixes** fixes #314 

Fix : Remote value file download fails when URL contains query strings

---

README.md
docs/Cloud Integration.md

A more clear explanation of how to use `vals` integration.
**Special notes for your reviewer**: only Markdown changes!

Docs revision

---

docs/Installation.md

Update version helm-secrets in docs

---

Dockerfile
tests/alpine.Dockerfile
tests/ubuntu.Dockerfile

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #324 

fix dockerfiles

---

scripts/lib/file.sh
tests/assets/values/sops/http.secrets.yaml
tests/assets/values/vals/http.secrets.yaml
tests/unit/template.bats

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #328 

Fix curl error with files begin with http

---

.gitignore
scripts/lib/common.sh
tests/lib/setup_suite.bash

try fix CI

---

CHANGELOG.md
scripts/commands/helm.sh
scripts/lib/backend.sh
tests/unit/template.bats

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #352

Fix: Exclamation mark in --set argument result into to backend not found error

---

docs/ArgoCD Integration.md
scripts/commands/downloader.sh
scripts/lib/common.sh

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #350 fixes #349 

Fix ArgoCD documentation for multi source applications

---

.github/workflows/ci.yaml
CHANGELOG.md
scripts/commands/helm.sh
scripts/lib/common.sh
scripts/lib/file/custom.sh
scripts/lib/file/helm-values-getter/templates/values.yaml
scripts/run.sh
tests/it/diff.bats
tests/it/install.bats
tests/it/upgrade.bats
tests/unit/lint.bats
tests/unit/template.bats

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #337

fix: Error on custom protocol value files which are not resolving into yaml files

---

scripts/wrapper/helm.sh
tests/assets/values/vals/templates/base/template.yaml
tests/unit/template.bats

**What this PR does / why we need it**: Cover potential issues from #365 

Add tests for post-renderer with envs

---

scripts/lib/backends/noop.sh
tests/unit/secret-backends.bats

noop driver should do nothing by default

---

docs/ArgoCD Integration.md

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #382

use new helm values structure

---

docs/ArgoCD Integration.md

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #396

Update ArgoCD Integration.md

---

CHANGELOG.md
scripts/commands/helm.sh
tests/unit/template.bats

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #404 

fix multiline parameter values

---

docs/Usage.md

I stumbled upon this small error in the docs, and thought I'd fix it. AFAICT it's an oversight from 5e419f07cb7a9a28c85eddd140abfc99714c2df2.

Update command names in usage summary

---

docs/ArgoCD Integration.md

I tried improving the docs a bit for people using age encryption with ArgoCD. Before it looked like `HELM_SECRETS_LOAD_GPG_KEYS` should be configured both for GPG and age. I tried to make it more clear that for age it should be `SOPS_AGE_KEY_FILE`, by adding examples for age.

docs: Improved docs readability for age

---

.github/workflows/ci.yaml

Remove CentOS 7 from CI tests.

---

USERS.md

added wuerth it gmbh to users

---

docs/ArgoCD Integration.md

Update helm-secrets schemes for argocd helm chart

---

docs/ArgoCD Integration.md

update github link for argocd helm chart

---

docs/ArgoCD Integration.md

Updated dockerfile and helm values to support amd64 and arm64

---

examples/terraform/helm.tf

**What this PR does / why we need it**: The code in the terraform example has a bad argument in the `helm secret` call. This PR corrects it.
**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #497
**Special notes for your reviewer**: I haven't modify the Changelog.md has it's just a small modification in an example.
Let me know if you think it's necessary.
Let me know if you think it's necessary.

Fix helm secret syntax in terraform example

---

.github/workflows/ci.yaml
renovate.json
tests/lib/helper.bash
tests/lib/setup_suite.bash
tests/unit/decrypt.bats

fix cygwin tests

---

.github/workflows/ci.yaml
tests/lib/helper.bash
tests/unit/template.bats

In releasing v4.6.6, we unintentionally broke behavior on Helm versions <3.18.0. It would be nice to update the CI tests so changes are also tested on previous versions of Helm.
This also adds Helm version checking to the unit tests, so certain tests that had behavior change between Helm versions can be skipped as needed.
Should be merged after #574, since that will fix the plugin.yaml for prior versions of Helm.

CI: Include tests for previous helm versions

---

.github/workflows/ci.yaml

run ci only on scripts

---

.github/workflows/ci.yaml
.gitmodules
plugin.yaml
tests/unit/template.bats

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #567 

Fix command syntax for Windows in plugin.yaml
